[workspace]
members = [
    "ow-common",
    "ow-executor",
    "ow-wasmtime-args",
    "ow-wasmtime-stdio",
    "ow-wasmtime-memory",
    "ow-wasmtime-component",
    "action-builder",
    "action-builder-component"
]

[profile.release]
lto = true